// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    PageContainer: typeof import('./src/components/PageContainer.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    VanCell: typeof import('vant/es')['Cell']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
  }
}

export { }
